# Generated by Django 3.2.6 on 2021-09-05 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('days', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='studentsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('standard', models.IntegerField()),
                ('section', models.CharField(max_length=10)),
                ('rollno', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='attendon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attended', models.BooleanField(default=False)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.attendmonth')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentslist')),
            ],
        ),
        migrations.AddField(
            model_name='attendmonth',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentslist'),
        ),
    ]
