# Generated by Django 3.2.9 on 2022-02-22 05:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('parent_name', models.CharField(max_length=255)),
                ('standard', models.IntegerField()),
                ('phone', models.BigIntegerField(null=True)),
                ('section', models.CharField(choices=[('A', 'science'), ('C', 'commerce'), ('H', 'humanity')], max_length=6)),
                ('rollno', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='json_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(default={'April': [30, 0], 'August': [31, 0], 'December': [31, 0], 'February': [28, 0], 'January': [31, 0], 'July': [31, 0], 'June': [30, 0], 'March': [31, 0], 'May': [31, 0], 'November': [30, 0], 'October': [31, 0], 'September': [30, 0]})),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentslist')),
            ],
        ),
        migrations.CreateModel(
            name='attendon',
            fields=[
                ('udate', models.TextField(max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('attended', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentslist')),
            ],
        ),
    ]
