# Generated by Django 2.2.24 on 2021-09-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendon',
            name='udate',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
