# Generated by Django 3.2.9 on 2022-03-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendon',
            name='udate',
            field=models.TextField(default=-345341, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='attendon',
            unique_together={('udate',)},
        ),
    ]
