# Generated by Django 3.2.9 on 2022-02-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='year_range',
            fields=[
                ('year', models.IntegerField(default=2022, primary_key=True, serialize=False)),
                ('range_data', models.TextField(default={'April': 30, 'August': 31, 'December': 31, 'February': 28, 'January': 31, 'July': 31, 'June': 30, 'March': 31, 'May': 31, 'November': 30, 'October': 31, 'September': 30})),
            ],
        ),
        migrations.AlterField(
            model_name='json_data',
            name='data',
            field=models.TextField(default={'April': 0, 'August': 0, 'December': 0, 'February': 0, 'January': 0, 'July': 0, 'June': 0, 'March': 0, 'May': 0, 'November': 0, 'October': 0, 'September': 0}),
        ),
    ]
