# Generated by Django 3.2.6 on 2021-09-05 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendon',
            name='month',
        ),
    ]
