# Generated by Django 2.2.20 on 2021-09-25 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendon',
            name='udate',
            field=models.CharField(default=datetime.date(2021, 9, 25), max_length=30),
        ),
    ]
