# Generated by Django 2.2.20 on 2021-09-25 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_attendon_udate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendon',
            name='id',
        ),
        migrations.RemoveField(
            model_name='attendon',
            name='udate',
        ),
        migrations.AlterField(
            model_name='attendon',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, primary_key=True, serialize=False),
        ),
    ]
