# Generated by Django 3.2.9 on 2022-01-01 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20210929_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='json_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(default={})),
            ],
        ),
        migrations.AlterField(
            model_name='studentslist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='attendMonth',
        ),
        migrations.AddField(
            model_name='json_data',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentslist'),
        ),
    ]
