# Generated by Django 2.2.20 on 2021-09-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_attendon_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendmonth',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attendon',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentslist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentslist',
            name='section',
            field=models.CharField(choices=[('A', 'science'), ('C', 'commerce'), ('H', 'humanity')], max_length=6),
        ),
    ]
