# Generated by Django 3.2.9 on 2025-03-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20220305_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year_range',
            name='year',
            field=models.IntegerField(default=2025, primary_key=True, serialize=False),
        ),
    ]
