# Generated by Django 3.2.9 on 2022-01-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20220102_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='json_data',
            name='data',
            field=models.TextField(default={'April': [30, 0], 'August': [31, 0], 'December': [31, 0], 'February': [28, 0, 29], 'January': [31, 0], 'July': [31, 0], 'June': [30, 0], 'March': [31, 0], 'May': [31, 0], 'November': [30, 0], 'October': [31, 0], 'September': [30, 0]}),
        ),
    ]
