# Generated by Django 2.2.20 on 2021-09-18 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20210916_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendon',
            name='date',
            field=models.DateField(default=datetime.date(2021, 9, 18)),
        ),
    ]
