# Generated by Django 2.2.20 on 2021-09-18 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20210918_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendon',
            name='id',
        ),
        migrations.AlterField(
            model_name='attendon',
            name='date',
            field=models.DateField(default=datetime.date(2021, 9, 18), primary_key=True, serialize=False),
        ),
    ]
