# Generated by Django 3.2.9 on 2022-01-15 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_json_data_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentslist',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='studentslist',
            name='father',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentslist',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='json_data',
            name='data',
            field=models.TextField(default={'April': [30, 0], 'August': [31, 0], 'December': [31, 0], 'February': [28, 0], 'January': [31, 0], 'July': [31, 0], 'June': [30, 0], 'March': [31, 0], 'May': [31, 0], 'November': [30, 0], 'October': [31, 0], 'September': [30, 0]}),
        ),
    ]
