# Generated by Django 3.2.9 on 2022-01-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20220116_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentslist',
            old_name='father',
            new_name='parent_name',
        ),
    ]
